apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
    - image: leeroy-app
      context: leeroy-app
test:
  - image: leeroy-app
    custom:
    - command: ./hack/scan.sh $IMAGE
deploy:
  kubectl:
    manifests:
      - leeroy-web/kubernetes/*
      - leeroy-app/kubernetes/*